[package]
name = "toetactic"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/prawnydagrate/toetactic"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
toetactic_lib = { path = "toetactic_lib" }

[[bin]]
name = "toetactic"
path = "src/main.rs"
